### ISSUE TITLE
Demonstration issues #2 (Memory) 

### ISSUE THREAD

**Issue by jeonhuhuhu** [notmahi/clip-fields#10]
Hi!

I experimented with a new environment using the Record3D App (Data size: 380MB). 

However, the process of loading and computing data in the Jupyter Notebook code (`1-parse rgbd.ipynb`), particularly in the first cell, consumes excessive memory.

<img src="https://github.com/notmahi/clip-fields/assets/148358798/e594911a-961d-4076-abe0-d9695b15280a" width="70%">

Although my computer has 256GB of memory, it nearly reaches around 200GB of usage. 

As a result, the Jupyter Notebook often crashes during the last code cell, which is responsible for saving the data as a `.pth` file. 

<img src="https://github.com/notmahi/clip-fields/assets/148358798/871209f0-5454-4ce8-8d8d-1226e2a7f581" width="70%">

Could you please share any possible solutions for this issue? 

Additionally, if I need more memory for experimenting with larger environments in the future,
how can I address this? 

For now, I plan to run the successful training code `python train.py dataset_path=nyu.r3d` instead of the Jupyter Notebook.

Thank you in advance for your kind response^^.

**Comment by notmahi** [comment]
Hi, the best thing to do in this situation is to record the r3d file at a lower fps, something like 10-15 has been fine for us in practice. That, compared to the default 60 fps, will lower memory requirements to at least a fourth already.

You can also consider subsampling frames from the current recording you have, which will require modifying some code, but would be better if it's hard to re-record.

**Comment by jeonhuhuhu** [comment]
> Hi, the best thing to do in this situation is to record the r3d file at a lower fps, something like 10-15 has been fine for us in practice. That, compared to the default 60 fps, will lower memory requirements by at least a fourth already.
> 
> You can also consider subsampling frames from the current recording you have, which will require modifying some code, but would be better if it's hard to re-record.


Thank you for your kind and prompt response. 

I am urgently adding more memory to match 1024GB for further experimentation. 

Additionally, I will conduct experiments by lowering the fps for individuals with smaller memory and will post the results accordingly. 

Thank you always for your prompt and kind responses!!!

**Comment by notmahi** [comment]
Hi, 1024 GB RAM really sounds like an overkill, and for anyone else reading this: if you are facing such huge RAM requirements please just lower the FPS.

Closing the issue now since it seems resolved.
