### ISSUE TITLE
Runtime Error

### ISSUE THREAD

**Issue by qiwen-1123** [notmahi/clip-fields#6]
Hi,
after I setting up the environment following the steps in the tutorial, there is a Runtime Error when I try to run the `python train.py dataset_path=nyu.r3d`, does anyone has the same problem? And I would like to kindly ask you what is your pytorch version, cause the `conda install -y pytorch torchvision torchaudio cudatoolkit=11.1 -c pytorch-lts -c nvidia` automatically installs the newest version of pytorch.

the following is the error report
`RuntimeError: Error building extension 'enclib_gpu': [1/3] /usr/local/cuda/bin/nvcc  -DTORCH_EXTENSION_NAME=enclib_gpu -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/qiwen/anaconda3/envs/cf/lib/python3.8/site-packages/torch/include -isystem /home/qiwen/anaconda3/envs/cf/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /home/qiwen/anaconda3/envs/cf/lib/python3.8/site-packages/torch/include/TH -isystem /home/qiwen/anaconda3/envs/cf/lib/python3.8/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /home/qiwen/anaconda3/envs/cf/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 --compiler-options '-fPIC' --expt-extended-lambda -std=c++17 -c /home/qiwen/anaconda3/envs/cf/lib/python3.8/site-packages/encoding/lib/gpu/lib_ssd.cu -o lib_ssd.cuda.o 
FAILED: lib_ssd.cuda.o 
/usr/local/cuda/bin/nvcc  -DTORCH_EXTENSION_NAME=enclib_gpu -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/qiwen/anaconda3/envs/cf/lib/python3.8/site-packages/torch/include -isystem /home/qiwen/anaconda3/envs/cf/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /home/qiwen/anaconda3/envs/cf/lib/python3.8/site-packages/torch/include/TH -isystem /home/qiwen/anaconda3/envs/cf/lib/python3.8/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /home/qiwen/anaconda3/envs/cf/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 --compiler-options '-fPIC' --expt-extended-lambda -std=c++17 -c /home/qiwen/anaconda3/envs/cf/lib/python3.8/site-packages/encoding/lib/gpu/lib_ssd.cu -o lib_ssd.cuda.o 
/home/qiwen/anaconda3/envs/cf/lib/python3.8/site-packages/encoding/lib/gpu/lib_ssd.cu:22:10: fatal error: THC/THCNumerics.cuh: No such file or directory
   22 | #include <THC/THCNumerics.cuh>
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
[2/3] /usr/local/cuda/bin/nvcc  -DTORCH_EXTENSION_NAME=enclib_gpu -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/qiwen/anaconda3/envs/cf/lib/python3.8/site-packages/torch/include -isystem /home/qiwen/anaconda3/envs/cf/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /home/qiwen/anaconda3/envs/cf/lib/python3.8/site-packages/torch/include/TH -isystem /home/qiwen/anaconda3/envs/cf/lib/python3.8/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /home/qiwen/anaconda3/envs/cf/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 --compiler-options '-fPIC' --expt-extended-lambda -std=c++17 -c /home/qiwen/anaconda3/envs/cf/lib/python3.8/site-packages/encoding/lib/gpu/rectify_cuda.cu -o rectify_cuda.cuda.o 
FAILED: rectify_cuda.cuda.o 
/usr/local/cuda/bin/nvcc  -DTORCH_EXTENSION_NAME=enclib_gpu -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/qiwen/anaconda3/envs/cf/lib/python3.8/site-packages/torch/include -isystem /home/qiwen/anaconda3/envs/cf/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /home/qiwen/anaconda3/envs/cf/lib/python3.8/site-packages/torch/include/TH -isystem /home/qiwen/anaconda3/envs/cf/lib/python3.8/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /home/qiwen/anaconda3/envs/cf/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 --compiler-options '-fPIC' --expt-extended-lambda -std=c++17 -c /home/qiwen/anaconda3/envs/cf/lib/python3.8/site-packages/encoding/lib/gpu/rectify_cuda.cu -o rectify_cuda.cuda.o 
/home/qiwen/anaconda3/envs/cf/lib/python3.8/site-packages/encoding/lib/gpu/rectify_cuda.cu(114): error: identifier "ScalarConvert" is undefined

/home/qiwen/anaconda3/envs/cf/lib/python3.8/site-packages/encoding/lib/gpu/rectify_cuda.cu(114): error: type name is not allowed

/home/qiwen/anaconda3/envs/cf/lib/python3.8/site-packages/encoding/lib/gpu/rectify_cuda.cu(114): error: type name is not allowed

/home/qiwen/anaconda3/envs/cf/lib/python3.8/site-packages/encoding/lib/gpu/rectify_cuda.cu(114): error: the global scope has no "to"

4 errors detected in the compilation of "/home/qiwen/anaconda3/envs/cf/lib/python3.8/site-packages/encoding/lib/gpu/rectify_cuda.cu".
ninja: build stopped: subcommand failed.`

**Comment by notmahi** [comment]
Hi! The pytorch version used for this project is 1.8.2.

Also, I am sorry for the errors, but seems like they are coming from the dependency, torch-encoding library here: [https://github.com/zhanghang1989/PyTorch-Encoding](https://github.com/zhanghang1989/PyTorch-Encoding). You may have better luck looking at their issues and documentations.

**Comment by qiwen-1123** [comment]
Hi,
many thanks, that fixed my issue.
But when I try to run the demo-1, I find that I have problems with the RAM, all 64 GB RAM on my laptop is taken up, then the program crashed. How much RAM were you using? And is there any way to reduce the needed RAM size.
Thanks in advance

**Comment by notmahi** [comment]
Hey, since that is a different issue more similar to #4 , I will close this one and continue the conversation there. Could you specify at which step your code is crashing on that thread?

I ran this model on a 256 GB cluster machine, so there may be times where bursts of memory was used without any issue.

**Comment by jeonhuhuhu** [comment]
> Hi, many thanks, that fixed my issue. But when I try to run the demo-1, I find that I have problems with the RAM, all 64 GB RAM on my laptop is taken up, then the program crashed. How much RAM were you using? And is there any way to reduce the needed RAM size. Thanks in advance


How did you resolve the issue mentioned above? 

We are using **PyTorch=2.2.1 with CUDA 11.8**, and the **PyTorch=1.8.2** version you mentioned is not supported in our environment.

**Comment by notmahi** [comment]
@jeonhuhuhu , it seems like the solution was to lower fps before processing: https://github.com/notmahi/clip-fields/issues/4#issuecomment-1697574050

You can lower the recording fps in the record3d app settings.

**Comment by ssspeg** [comment]
> 你好， 我按照教程中的步骤设置环境后，尝试运行时出现运行时错误`python train.py dataset_path=nyu.r3d`，有人遇到同样的问题吗？我想问一下你的 pytorch 版本是什么，因为我会`conda install -y pytorch torchvision torchaudio cudatoolkit=11.1 -c pytorch-lts -c nvidia`自动安装最新版本的 pytorch。
> 
> 以下是错误报告 `RuntimeError: Error building extension 'enclib_gpu': [1/3] /usr/local/cuda/bin/nvcc -DTORCH_EXTENSION_NAME=enclib_gpu -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=" _gcc" -DPYBIND11_STDLIB=" _libstdcpp" -DPYBIND11_BUILD_ABI=" _cxxabi1011" -isystem /home/qiwen/anaconda3/envs/cf/lib/python3.8/site-packages/torch/include -isystem /home/qiwen/anaconda3/envs/cf/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /home/qiwen/anaconda3/envs/cf/lib/python3.8/site-packages/torch/include/TH -isystem /home/qiwen/anaconda3/envs/cf/lib/python3.8/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /home/qiwen/anaconda3/envs/cf/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS_ _ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 --compiler-options '-fPIC' --expt-extended-lambda -std=c++17 -c /home/qiwen/anaconda3/envs/cf/lib/python3.8/site-packages/encoding/lib/gpu/lib_ssd.cu -o lib_ssd.cuda.o 失败：lib_ssd.cuda.o /usr/local/cuda/bin/nvcc -DTORCH_EXTENSION_NAME=enclib_gpu -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=" _gcc" -DPYBIND11_STDLIB=" _libstdcpp" -DPYBIND11_BUILD_ABI=" _cxxabi1011" -isystem /home/qiwen/anaconda3/envs/cf/lib/python3.8/site-packages/torch/include -isystem /home/qiwen/anaconda3/envs/cf/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /home/qiwen/anaconda3/envs/cf/lib/python3.8/site-packages/torch/include/TH -isystem /home/qiwen/anaconda3/envs/cf/lib/python3.8/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /home/qiwen/anaconda3/envs/cf/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS_ _ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 --compiler-options '-fPIC' --expt-extended-lambda -std=c++17 -c /home/qiwen/anaconda3/envs/cf/lib/python3.8/site-packages/encoding/lib/gpu/lib_ssd.cu -o lib_ssd.cuda.o /home/qiwen/anaconda3/envs/cf/lib/python3.8/site-packages/encoding/lib/gpu/lib_ssd.cu:22:10: 致命错误：THC/THCNumerics.cuh：没有此文件或目录 22 | #包括 <THC/THCNumerics.cuh> | ^~~~~~~~~~~~~~~~~~~~~~~~~ 编译终止。 [2/3] /usr/local/cuda/bin/nvcc -DTORCH_EXTENSION_NAME=enclib_gpu -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=" _gcc" -DPYBIND11_STDLIB=" _libstdcpp" -DPYBIND11_BUILD_ABI="_cxxabi1011“-isystem /home/qiwen/anaconda3/envs/cf/lib/python3.8/site-packages/torch/include -isystem /home/qiwen/anaconda3/envs/cf/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /home/qiwen/anaconda3/envs/cf/lib/python3.8/site-packages/torch/include/TH -isystem /home/qiwen/anaconda3/envs/cf/lib/python3.8/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /home/qiwen/anaconda3/envs/cf/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 --compiler-options '-fPIC' --expt-extended-lambda -std=c++17 -c /home/qiwen/anaconda3/envs/cf/lib/python3.8/site-packages/encoding/lib/gpu/rectify_cuda.cu -o rectify_cuda.cuda.o 失败：rectify_cuda.cuda.o /usr/local/cuda/bin/nvcc -DTORCH_EXTENSION_NAME=enclib_gpu -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE="_gcc" -DPYBIND11_STDLIB="_ libstdcpp" -DPYBIND11_BUILD_ABI=" _cxxabi1011" -isystem /home/qiwen/anaconda3/envs/cf/lib/python3.8/site-packages/torch/include -isystem /home/qiwen/anaconda3/envs/cf/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /home/qiwen/anaconda3/envs/cf/lib/python3.8/site-packages/torch/include/TH -isystem /home/qiwen/anaconda3/envs/cf/lib/python3.8/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /home/qiwen/anaconda3/envs/cf/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 --compiler-options '-fPIC' --expt-extended-lambda -std=c++17 -c /home/qiwen/anaconda3/envs/cf/lib/python3.8/site-packages/encoding/lib/gpu/rectify_cuda.cu -o rectify_cuda.cuda.o /home/qiwen/anaconda3/envs/cf/lib/python3.8/site-packages/encoding/lib/gpu/rectify_cuda.cu(114): 错误：标识符“ScalarConvert”未定义
> 
> /home/qiwen/anaconda3/envs/cf/lib/python3.8/site-packages/encoding/lib/gpu/rectify_cuda.cu(114): 错误：类型名称不允许
> 
> /home/qiwen/anaconda3/envs/cf/lib/python3.8/site-packages/encoding/lib/gpu/rectify_cuda.cu(114): 错误：类型名称不允许
> 
> /home/qiwen/anaconda3/envs/cf/lib/python3.8/site-packages/encoding/lib/gpu/rectify_cuda.cu(114): 错误：全局范围没有“to”
> 
> 在“/home/qiwen/anaconda3/envs/cf/lib/python3.8/site-packages/encoding/lib/gpu/rectify_cuda.cu”的编译中检测到 4 个错误。ninja ：构建已停止：子命令失败。`
Hi, I have encountered the same issue as you. How did you resolve it?
