### ISSUE TITLE
Installation issues #1 (CUDA, Detectron2, etc)

### ISSUE THREAD

**Issue by jeonhuhuhu** [notmahi/clip-fields#7]
We are using an RTX 3060 ti GPU, and unfortunately, we are unable to install **CUDA versions 11.1-11.3**. 

Therefore, we are attempting to experiment with CUDA 11.8 or higher versions to install the Detectron2 code. 

If you have any experience with such a task, would you be willing to share your valuable experience with us?"

- OS: Ubuntu 20.04 LTS
- GPU: RTX 3060 ti
- CUDA: 11.8 (Unable to install CUDA versions 11.1-11.3 because of CUDA GPUs Compute Capability)

-------------------------------------------------------------
"We are interested in running the OK-Robot code to explore its capabilities. In doing so, we aim to recognize scenes in a new environment and perform robot tasks, which leads us to believe that the CLIP-Fields model is necessary. 

However, we noticed that the OK-Robot uploaded a few days ago does not require the installation of the CLIP-Fields model on this page(https://github.com/ok-robot/ok-robot?tab=readme-ov-file). 

Could you kindly confirm if this is the case?"

Thank you in advance for your kind cooperation

**Comment by notmahi** [comment]
Hello and thank you for your interest! One possible solution is to change [Line 9](https://github.com/notmahi/clip-fields/blob/main/gridencoder/setup.py#L9) and [Line 16](https://github.com/notmahi/clip-fields/blob/main/gridencoder/setup.py#L16) in the setup file from `-std=c++14` to `-std=c++17`. Could you try it and let us know if it works?

On other news, in the OK-Robot paper, we compared CLIP-Fields to VoxelMap in 3 lab environments and found that VoxelMap performs slightly better. Given that VoxelMap doesn't require training, we chose that for the final OK-Robot implementation. Hope that is relevant information for you.

**Comment by jeonhuhuhu** [comment]
> Hello and thank you for your interest! One possible solution is to change [Line 9](https://github.com/notmahi/clip-fields/blob/main/gridencoder/setup.py#L9) and [Line 16](https://github.com/notmahi/clip-fields/blob/main/gridencoder/setup.py#L16) in the setup file from `-std=c++14` to `-std=c++17`. Could you try it and let us know if it works?
> 
> On other news, in the OK-Robot paper, we compared CLIP-Fields to VoxelMap in 3 lab environments and found that VoxelMap performs slightly better. Given that VoxelMap doesn't require training, we chose that for the final OK-Robot implementation. Hope that is relevant information for you.

Thanks for your quick reply. 

I followed your advice, but the error still occurs. 

**[Installation maunal]**
After setup file from `-std=c++14` to `-std=c++17`, 

1. conda create -n cf python=3.8
2. conda install pytorch torchvision torchaudio pytorch-cuda=11.8 -c pytorch -c nvidia
3. pip install -r requirements.txt
4. TORCH_CUDA_ARCH_LIST="8.6" python setup.py install

We have confirmed that the installation was successful.
![Screenshot from 2024-02-27 15-02-31](https://github.com/notmahi/clip-fields/assets/148358798/ea1c1374-6bea-427f-aeda-76cbe9459b14)

Several existing errors have been resolved through this question, but the error below has not been resolved.

**[Issues]**

- OS: Ubuntu 20.04 LTS
- GPU: RTX 3060 ti
- CUDA: 11.8 (CUDA GPUs Compute Capability=8.6)
- pytorch: 2.2.1 / torchaudio: 2.2.1 / torchvision: 0.17.1   

When we run code `python train.py dataset_path=nyu.r3d`,

![Screenshot from 2024-02-27 15-06-07](https://github.com/notmahi/clip-fields/assets/148358798/5e628b81-a179-4e8d-aa65-98d408da04ea)

It seems that switching `from c++14 to c++17` is causing errors, and despite searching for solutions, we haven't been able to resolve them. 

We have confirmed that the issue lies with the CUDA and PyTorch versions. 

Since we are using `PyTorch=2.2.1 with CUDA=11.8`, downgrading to `PyTorch=1.8.2` is not straightforward. 

Therefore, we are looking for a solution. 

Do you know of any?

Would it be better to try VoxelMap directly instead of the CLIP-Field Model?

Thank you in advance for your kind cooperation

--------------------------------------------------------------------------------------------------

We successfully completed the installation over the course of approximately three days, 
including Ubuntu 20.04 + CUDA 11.8. ^^

**Comment by notmahi** [comment]
Hi @jeonhuhuhu , could you please tell us what you did to resolve it? Just so we have a solution posted here that future users can use.

**Comment by jarvishou829** [comment]
> > Hello and thank you for your interest! One possible solution is to change [Line 9](https://github.com/notmahi/clip-fields/blob/main/gridencoder/setup.py#L9) and [Line 16](https://github.com/notmahi/clip-fields/blob/main/gridencoder/setup.py#L16) in the setup file from `-std=c++14` to `-std=c++17`. Could you try it and let us know if it works?
> > On other news, in the OK-Robot paper, we compared CLIP-Fields to VoxelMap in 3 lab environments and found that VoxelMap performs slightly better. Given that VoxelMap doesn't require training, we chose that for the final OK-Robot implementation. Hope that is relevant information for you.
> 
> Thanks for your quick reply.
> 
> I followed your advice, but the error still occurs.
> 
> **[Installation maunal]** After setup file from `-std=c++14` to `-std=c++17`,
> 
> 1. conda create -n cf python=3.8
> 2. conda install pytorch torchvision torchaudio pytorch-cuda=11.8 -c pytorch -c nvidia
> 3. pip install -r requirements.txt
> 4. TORCH_CUDA_ARCH_LIST="8.6" python setup.py install
> 
> We have confirmed that the installation was successful. ![Screenshot from 2024-02-27 15-02-31](https://private-user-images.githubusercontent.com/148358798/308054942-ea1c1374-6bea-427f-aeda-76cbe9459b14.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyNzc0ODYsIm5iZiI6MTcwOTI3NzE4NiwicGF0aCI6Ii8xNDgzNTg3OTgvMzA4MDU0OTQyLWVhMWMxMzc0LTZiZWEtNDI3Zi1hZWRhLTc2Y2JlOTQ1OWIxNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwMVQwNzEzMDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YzliZDRhYjVkNmU5NjQxNzk0ZDJmYmQ1ZDQwMmJhZDEyOGQ2YWM0OTMzZGJhYjMyODFjNzk1MjE3Zjk2OWZkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2BLKRdrlbtE2gnI3iDV37U0-l4E1UNfiqwlGkRnpCUs)
> 
> Several existing errors have been resolved through this question, but the error below has not been resolved.
> 
> **[Issues]**
> 
> * OS: Ubuntu 20.04 LTS
> * GPU: RTX 3060 ti
> * CUDA: 11.8 (CUDA GPUs Compute Capability=8.6)
> * pytorch: 2.2.1 / torchaudio: 2.2.1 / torchvision: 0.17.1
> 
> When we run code `python train.py dataset_path=nyu.r3d`,
> 
> ![Screenshot from 2024-02-27 15-06-07](https://private-user-images.githubusercontent.com/148358798/308055760-5e628b81-a179-4e8d-aa65-98d408da04ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyNzc0ODYsIm5iZiI6MTcwOTI3NzE4NiwicGF0aCI6Ii8xNDgzNTg3OTgvMzA4MDU1NzYwLTVlNjI4YjgxLWExNzktNGU4ZC1hYTY1LTk4ZDQwOGRhMDRlYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwMVQwNzEzMDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNmFkMjAxZGFiNDRlMTcwZjliMmNiYTBmYzlhZTI5Yjg1ZGY4OWVlZTlmZjg5ODNmNjQ3Y2JkNzU3MjJhOTAxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Lt5cwRI7sdXyKv3C2p644o_ChW5srQTdCJmmQ37rCrA)
> 
> It seems that switching `from c++14 to c++17` is causing errors, and despite searching for solutions, we haven't been able to resolve them.
> 
> We have confirmed that the issue lies with the CUDA and PyTorch versions.
> 
> Since we are using `PyTorch=2.2.1 with CUDA=11.8`, downgrading to `PyTorch=1.8.2` is not straightforward.
> 
> Therefore, we are looking for a solution.
> 
> Do you know of any?
> 
> Would it be better to try VoxelMap directly instead of the CLIP-Field Model?
> 
> Thank you in advance for your kind cooperation
> 
> We successfully completed the installation over the course of approximately three days, including Ubuntu 20.04 + CUDA 11.8. ^^

I met the same problem that "ScalarConvert" is undefined. Could you please help me how you fix it?

**Comment by notmahi** [comment]
Hi @jarvishou829 , if you are still struggling with this, you can try commenting out these three lines: https://github.com/notmahi/clip-fields/blob/494d5508adbbe61db7f057ad8b9633c8b96bbd53/dataloaders/real_dataset.py#L39-L41

If you are not using LSeg (as most people are not), you should be fine doing so.

Please let me know if this fixes your problem.

**Comment by jarvishou829** [comment]
> Hi @jarvishou829 , if you are still struggling with this, you can try commenting out these three lines:
> 
> https://github.com/notmahi/clip-fields/blob/494d5508adbbe61db7f057ad8b9633c8b96bbd53/dataloaders/real_dataset.py#L39-L41
> 
> If you are not using LSeg (as most people are not), you should be fine doing so.
> 
> Please let me know if this fixes your problem.

Thanks for the advice. But after trying the solutions as far as I could find, finally I solve the " 'ScalarConvert' is undefined" problem by applying [these changes](https://github.com/zhanghang1989/PyTorch-Encoding/pull/418/files).

**Comment by notmahi** [comment]
Glad to see it was resolved upstream! I’ll try to change the repo to use this version of encoding.

**Comment by notmahi** [comment]
Updated the requirements and readme with the fix in commit https://github.com/notmahi/clip-fields/commit/7edfa8562b1337d7b73bf700968e8b74323b8b9e

**Comment by jeonhuhuhu** [comment]
> Hi @jeonhuhuhu , could you please tell us what you did to resolve it? Just so we have a solution posted here that future users can use.

My apologies for the delayed response due to the extended holiday. 

I have outlined the solution below. 
The issue I encountered was the inability to install "PyTorch-Encoding." Thus, the installation solution is

1. git clone https://github.com/zhanghang1989/PyTorch-Encoding && cd PyTorch-Encoding
2. python setup.py install
![image](https://github.com/notmahi/clip-fields/assets/148358798/e211ba79-2e63-4b88-9a4c-1461a910e9e3)

Starting with steps 1 and 2 directly will lead to an error. 

The solution I found was quite frustrating, 
but simply uninstalling the existing "torch-encoding" and then reinstalling it resolved the issue immediately. 

It was a surprisingly simple solution, and the exact same answer was found on the following GitHub page.
https://github.com/zhanghang1989/PyTorch-Encoding/issues/424 

1. pip uninstall torch-encoding
2. pip install torch-encoding

I hope this post serves as a solution for someone.

**Comment by jeonhuhuhu** [comment]
> > > Hello and thank you for your interest! One possible solution is to change [Line 9](https://github.com/notmahi/clip-fields/blob/main/gridencoder/setup.py#L9) and [Line 16](https://github.com/notmahi/clip-fields/blob/main/gridencoder/setup.py#L16) in the setup file from `-std=c++14` to `-std=c++17`. Could you try it and let us know if it works?
> > > On other news, in the OK-Robot paper, we compared CLIP-Fields to VoxelMap in 3 lab environments and found that VoxelMap performs slightly better. Given that VoxelMap doesn't require training, we chose that for the final OK-Robot implementation. Hope that is relevant information for you.
> > 
> > 
> > Thanks for your quick reply.
> > I followed your advice, but the error still occurs.
> > **[Installation maunal]** After setup file from `-std=c++14` to `-std=c++17`,
> > 
> > 1. conda create -n cf python=3.8
> > 2. conda install pytorch torchvision torchaudio pytorch-cuda=11.8 -c pytorch -c nvidia
> > 3. pip install -r requirements.txt
> > 4. TORCH_CUDA_ARCH_LIST="8.6" python setup.py install
> > 
> > We have confirmed that the installation was successful. ![Screenshot from 2024-02-27 15-02-31](https://private-user-images.githubusercontent.com/148358798/308054942-ea1c1374-6bea-427f-aeda-76cbe9459b14.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyNzc0ODYsIm5iZiI6MTcwOTI3NzE4NiwicGF0aCI6Ii8xNDgzNTg3OTgvMzA4MDU0OTQyLWVhMWMxMzc0LTZiZWEtNDI3Zi1hZWRhLTc2Y2JlOTQ1OWIxNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwMVQwNzEzMDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YzliZDRhYjVkNmU5NjQxNzk0ZDJmYmQ1ZDQwMmJhZDEyOGQ2YWM0OTMzZGJhYjMyODFjNzk1MjE3Zjk2OWZkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2BLKRdrlbtE2gnI3iDV37U0-l4E1UNfiqwlGkRnpCUs)
> > Several existing errors have been resolved through this question, but the error below has not been resolved.
> > **[Issues]**
> > 
> > * OS: Ubuntu 20.04 LTS
> > * GPU: RTX 3060 ti
> > * CUDA: 11.8 (CUDA GPUs Compute Capability=8.6)
> > * pytorch: 2.2.1 / torchaudio: 2.2.1 / torchvision: 0.17.1
> > 
> > When we run code `python train.py dataset_path=nyu.r3d`,
> > ![Screenshot from 2024-02-27 15-06-07](https://private-user-images.githubusercontent.com/148358798/308055760-5e628b81-a179-4e8d-aa65-98d408da04ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyNzc0ODYsIm5iZiI6MTcwOTI3NzE4NiwicGF0aCI6Ii8xNDgzNTg3OTgvMzA4MDU1NzYwLTVlNjI4YjgxLWExNzktNGU4ZC1hYTY1LTk4ZDQwOGRhMDRlYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwMVQwNzEzMDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNmFkMjAxZGFiNDRlMTcwZjliMmNiYTBmYzlhZTI5Yjg1ZGY4OWVlZTlmZjg5ODNmNjQ3Y2JkNzU3MjJhOTAxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Lt5cwRI7sdXyKv3C2p644o_ChW5srQTdCJmmQ37rCrA)
> > It seems that switching `from c++14 to c++17` is causing errors, and despite searching for solutions, we haven't been able to resolve them.
> > We have confirmed that the issue lies with the CUDA and PyTorch versions.
> > Since we are using `PyTorch=2.2.1 with CUDA=11.8`, downgrading to `PyTorch=1.8.2` is not straightforward.
> > Therefore, we are looking for a solution.
> > Do you know of any?
> > Would it be better to try VoxelMap directly instead of the CLIP-Field Model?
> > Thank you in advance for your kind cooperation
> > We successfully completed the installation over the course of approximately three days, including Ubuntu 20.04 + CUDA 11.8. ^^
> 
> I met the same problem that "ScalarConvert" is undefined. Could you please help me how you fix it?

Did you solve this problem? 

This is a "PyTorch-Encoding" installation issue, so I posted a new solution.
