### ISSUE TITLE
Demonstration issues #1 (Dataset)

### ISSUE THREAD

**Issue by jeonhuhuhu** [notmahi/clip-fields#9]
After following the installation process on your GitHub,
and completing the training up to Jupyter Notebook `4-test model.ipynb`  demo, 

After obtaining new data from the Record3D App and converting it to `.r3d format`,
I encountered an error when running the code in Jupyter Notebook `1-parse rgbd.ipynb` . 

<img src="https://github.com/notmahi/clip-fields/assets/148358798/4e2ba417-6df3-4a98-8be4-7e2ecf5fd768" width="70%">

I tried various methods to acquire the data and solve the issue, but it seems to be an issue with the input data itself. 

Is there any additional setting when acquiring data from the app, or do I have to use an `iPhone 13 Pro`? 

I obtained the data using an iPhone 14+, so I'm wondering if there might be compatibility 

If you are training using your `nyu.r3d` dataset, the computation progresses well.

<img src="https://github.com/notmahi/clip-fields/assets/148358798/ab108583-d032-4187-a7fa-e1c4169f493c" width="70%">

Thank you in advance.

**Comment by notmahi** [comment]
Hi @jeonhuhuhu , from the shape it looks like your data may be of resolution `640x480`, could you try after changing the line to `depth_img = depth_img.reshape((640, 480))` and see if that gives reasonable results? 

Just as a side note, at the higher resolution, to not run out of RAM you may also have to reduce `subsample_prob` when constructing the `DeticDenseLabelledDataset`.

**Comment by jeonhuhuhu** [comment]
> Hi @jeonhuhuhu , from the shape it looks like your data may be of resolution `640x480`, could you try after changing the line to `depth_img = depth_img.reshape((640, 480))` and see if that gives reasonable results?
> 
> Just as a side note, at the higher resolution, to not run out of RAM you may also have to reduce `subsample_prob` when constructing the `DeticDenseLabelledDataset`.


Thank you, I had already identified and resolved the resolution(`640x480`) issue in the video before your response, but I encountered another issue with the input data.^^

<img src="https://github.com/notmahi/clip-fields/assets/148358798/54dc92a6-e16c-49ff-a947-a27f5ad0222f" width="70%">

----------------------------------------

It seems that the `.conf` files are not being generated. 

I'm not sure if this is because I'm using the free version, but when I attempt to shoot and export, only two types of data are generated as shown in the image below (`depth, jpg`)."

<img src="https://github.com/notmahi/clip-fields/assets/148358798/cef848a7-e4bd-4863-b670-6117a941e198" width="50%">

I am currently investigating whether the `.conf` files are not generated because of my improper settings or if it's because I'm using the free version rather than the paid version. 

My settings are as shown in the diagram below.

<img src="https://github.com/notmahi/clip-fields/assets/148358798/c44332b4-dd3c-42d5-9617-14940a4a6e70" width="80%"> 

I would appreciate it if you could share how you configured the settings mentioned above.

It would be greatly appreciated if everyone could also share their experiences of acquiring their own real data and applying it to your model for testing purposes. 

Thank you in advance for sharing, and thank you in advance for your help.

**Comment by notmahi** [comment]
Hi @jeonhuhuhu , that looks like an issue with the record3d app that I am not an expert in. Could you ask this question in a new issue on the record3d repo or by emailing the author? The library author is generally very responsive.

You can find the email address on this website (contact link) https://record3d.app/, and here's the repo link: https://github.com/marek-simonik/record3d

I'm gonna close this issue now since we solved the original problem.
